config/routes.rb
Rails.application.routes.draw do
  

  namespace :api, defaults: {format: :json} do
    resources :questions, only: [:create, :update, :destroy, :show, :index]
    resources :answers, only: [:create, :update, :destroy]
    resources :answerchoices, only: [:create, :update, :destroy]
    resources :poll_rooms, only: [:create, :index, :show, :update, :destroy]
  end

  root to: 'staticpages#root'
  resources :users
  resource :session
  post '/users/guest', to: 'users#guest'
  get '/helloworld/', to: 'api/questions#helloworld', as: 'helloworld', defaults: {format: :json}

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
include ApplicationHelper
  def root
    # @question = current_question
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/root.html.erb
<!-- <%= link_to "hello", helloworld_url %> -->
<div id="splash">
  <div class="backdrop">
    <h1 id="title"><strong>Real-time Polls</strong></h1>
    <h4 id="descriptor">See what people are thinking now</h4>    
  
  
    <a class="poll-button" href='/#/questions/home'><button class='btn btn-default'>Check Out the Current Poll!</button></a>
    <form action='/users/guest' method='post'>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <label ><br>
    	<button id='splash-login' class='btn btn-default'>Guest Sign Up</button>
    </form>
    <!-- <a class="poll-button" href='/#/questions/home'><button class='btn btn-default'>Guest Login</button></a> -->
  </div>
  
</div>
<script>
window.currentUser = <%= current_user.to_json.html_safe %>;
window.currentQuestion = <%= current_question.to_json.html_safe %>;
window.questionTimer = <%= Time.now().to_i - current_question.updated_at.to_i %>
//make a voted global
</script>
<script>$(OmniPoll.initialize);</script>