config/routes.rb
Rails.application.routes.draw do
  

  namespace :api, defaults: {format: :json} do
    resources :questions, only: [:create, :update, :destroy, :show, :index]
    resources :answers, only: [:create, :update, :destroy]
    resources :answerchoices, only: [:create, :update, :destroy]
    resources :poll_rooms, only: [:create, :index, :show, :update, :destroy]
  end

  root to: 'staticpages#root'
  resources :users
  resource :session
  post '/users/guest', to: 'users#guest'
  get '/helloworld/', to: 'api/questions#helloworld', as: 'helloworld', defaults: {format: :json}

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= image_tag "logo2.png" %>
    <a class="navbar-brand" href="/#/questions/home">OmniPoll</a>
  </div>


<!--link to modals -->
  <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
    <% if signed_in? %>
    <li><a class='text-left' href="/#/questions/history"><button class='btn btn-default navbar-btn'>
      Past Polls</button></a></li>
    <li>
  <%= button_to "Sign out", session_url, method: :delete, class: "btn btn-default navbar-btn" %>
  </li>
    <% else %>
      <li><%= button_to "Log in", new_session_url, method: :get, class: "btn btn-default navbar-btn" %></li>
      <li><%= button_to "Sign up", new_user_url, method: :get, class: "btn btn-default navbar-btn" %></li>
    </ul>
    <% end %>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert">
     <span aria-hidden="true">&times;</span><span class="sr-only">Close
     </span></button>
<%= flash[:errors].join("<br>") %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Omnipoll</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="//js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>
</head>
<body>
<%= render partial: "layouts/header" %>

<div id="main" class='container'>
  <%= yield %>
</div>

</body>
</html>